server:
  port: 9091
spring:
  application:
    name: msa-architecture-eureka
    
#Config Server      
  cloud:
    config:
      uri: http://localhost:8888 
      name: msa-architecture-config-server
      
#Eureka Standalone Server       
eureka:
  client:
    registerWithEureka: true  #유레카 서버에 본인 서비스를 등록할 건지 여부
    fetchRegistry: false       #유레카 서버로부터 서비스 목록을 로컬 캐시에 저장할 건지 여부
    serviceUrl:
      defaultZone: http://localhost:${server.port}/eureka/
      