server:
  port: 8888
  
spring:
  application:
    name: msa-architecture-config
    
  cloud:
    config:
      server:
        git:
          uri: https://github.com/altjdtkdgh/LEESANGHO-STUDY.git
         # uri: https://github.com/altjdtkdgh/LEESANGHO-STUDY/tree/master/project/MSA_coffe/
         # searchPaths: boardService
          #https://github.com/altjdtkdgh/LEESANGHO-STUDY.git
      