server:
  port: 8083

spring:
  application:
    name: msa-service-board

#Config Server      
  cloud:
    config:
      uri: http://localhost:8888 
      name: msa-architecture-config-server

#Eureka Client   
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9091/eureka/
      
